server:
  port: 4200
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/concessionaria
    username: postgres
    password: p0k3m0n
  jpa:
    generate-ddl: true